-- Inserimento competenze di base per BOSTARTER
-- Da eseguire dopo la creazione del database

USE bostarter_compliant;

-- Competenze di programmazione
INSERT INTO competenze (nome) VALUES 
('JavaScript'),
('Python'),
('Java'),
('C++'),
('C#'),
('PHP'),
('HTML/CSS'),
('React'),
('Vue.js'),
('Angular'),
('Node.js'),
('Express.js'),
('Django'),
('Flask'),
('Spring Boot'),
('Laravel'),
('MySQL'),
('PostgreSQL'),
('MongoDB'),
('Redis'),
('Docker'),
('Kubernetes'),
('AWS'),
('Azure'),
('Google Cloud'),
('Linux'),
('Git'),
('Jenkins'),
('CI/CD'),
('Machine Learning'),
('Deep Learning'),
('Data Science'),
('AI'),
('Unity'),
('Unreal Engine'),
('Mobile Development'),
('iOS Development'),
('Android Development'),
('Flutter'),
('React Native'),
('UI/UX Design'),
('Graphic Design'),
('3D Modeling'),
('Blender'),
('Photoshop'),
('Illustrator'),
('Project Management'),
('Agile/Scrum'),
('DevOps'),
('Cybersecurity'),
('Blockchain'),
('IoT'),
('Embedded Systems'),
('Arduino'),
('Raspberry Pi'),
('Electronics'),
('Hardware Design'),
('PCB Design'),
('CAD'),
('Mechanical Engineering'),
('3D Printing'),
('Robotics'),
('Automation'),
('Testing/QA'),
('API Development'),
('Microservices'),
('System Architecture'),
('Database Design'),
('Network Security'),
('Cloud Architecture');

-- Verifica inserimento
SELECT COUNT(*) as total_competenze FROM competenze;
SELECT * FROM competenze ORDER BY nome LIMIT 10;
